Mwect4 18
purwadhikafullstack/JCWD011004 pull request #9
Opened 2023-09-13 05:53 UTC by AndreAdyatmoko

2023-09-13 17:38 UTC, dikokartiko approved these changes

2023-09-13 22:24 UTC, gianseptianlattang approved these changes, later dismissed

2023-09-13 22:29 UTC, gianseptianlattang reviewed
There is conflict before merge. please rebase from development and push again

2023-09-13 23:10 UTC, gianseptianlattang requested changes
![Screenshot 2023-09-14 060653](https://github.com/purwadhikafullstack/JCWD011004/assets/81907224/f4ea77eb-9cf6-441d-96d0-7ee090e03cb1)
Yg di API most Sales, kurang dkit ndre. Yg aku lingkarin

2023-09-14 04:08 UTC, AndreAdyatmoko commented
<img width="261" alt="Screenshot 2023-09-14 110644" src="https://github.com/purwadhikafullstack/JCWD011004/assets/132354161/0b358b13-fb6d-49fd-94c0-ef011152f0a7">


sudah aku perbaiki bang, ini kemrain confict karena untuk developmentku belum yang paling baru.

2023-09-14 08:43 UTC, gianseptianlattang approved these changes

2023-09-14 15:14 UTC, merged